#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import tempfile
import urllib.parse
from pathlib import Path
from typing import Any

from dependency_governance import (
    GitHubApi,
    GovernanceError,
    classify_ecosystem,
    load_config,
    validate_provenance,
    validate_signed_metadata,
)
from validate_dependency_locks import PIN_RE, canonical_name, load_direct_requirements, marker_environment

EXPECTED_PYTHONS = ("3.11", "3.12", "3.13", "3.14")
WORKFLOW_NAME = "dependency-locks"
WORKFLOW_PATH = ".github/workflows/dependency-locks.yml"
ARTIFACT_PREFIX = "python-"
ARTIFACT_SUFFIX = "-lock"
LOCK_LIMIT_BYTES = 5 * 1024 * 1024
PUBLISH_MESSAGE = "chore: refresh generated dependency locks"


def git_blob_sha_bytes(data: bytes) -> str:
    header = f"blob {len(data)}\0".encode()
    return hashlib.sha1(header + data).hexdigest()


def validate_workflow_run(
    workflow_run: dict[str, Any],
    pull: dict[str, Any],
    repository: str,
) -> None:
    reasons: list[str] = []
    if workflow_run.get("name") != WORKFLOW_NAME:
        reasons.append("workflow-run name is not dependency-locks")
    if workflow_run.get("path") != WORKFLOW_PATH:
        reasons.append("workflow-run path is not the trusted dependency-locks workflow")
    if workflow_run.get("event") != "pull_request":
        reasons.append("dependency-lock publisher accepts pull_request runs only")
    if workflow_run.get("conclusion") != "success":
        reasons.append("dependency-lock generation did not succeed")
    head_repository = workflow_run.get("head_repository") or {}
    if head_repository.get("full_name") != repository:
        reasons.append("workflow-run head repository is not the current repository")

    head = pull.get("head") or {}
    if workflow_run.get("head_sha") != head.get("sha"):
        reasons.append("workflow-run head SHA does not equal the current pull-request head")
    if workflow_run.get("head_branch") != head.get("ref"):
        reasons.append("workflow-run head branch does not equal the current pull-request branch")
    associations = workflow_run.get("pull_requests") or []
    if len(associations) != 1 or associations[0].get("number") != pull.get("number"):
        reasons.append("workflow run is not uniquely associated with the target pull request")
    if reasons:
        raise GovernanceError("unsafe dependency-lock workflow run:\n- " + "\n- ".join(reasons))


def _validate_lock_text(
    *,
    python_version: str,
    text: str,
    direct_requirements: list[Any],
) -> None:
    expected_header = f"autogenerated by pip-compile with Python {python_version}"
    if expected_header not in text:
        raise GovernanceError(f"Python {python_version} lock has the wrong generator header")
    if "--hash=sha256:" not in text:
        raise GovernanceError(f"Python {python_version} lock contains no package hashes")

    pins = {canonical_name(name): version for name, version in PIN_RE.findall(text)}
    if not pins:
        raise GovernanceError(f"Python {python_version} lock contains no exact package pins")

    environment = marker_environment(python_version)
    for requirement in direct_requirements:
        if requirement.marker and not requirement.marker.evaluate(environment=environment):
            continue
        name = canonical_name(requirement.name)
        pinned = pins.get(name)
        if pinned is None:
            raise GovernanceError(
                f"Python {python_version} lock is missing direct requirement {requirement.name}"
            )
        if requirement.specifier and not requirement.specifier.contains(pinned, prereleases=True):
            raise GovernanceError(
                f"Python {python_version} lock pins {requirement.name}=={pinned}, "
                f"outside source constraint {requirement.specifier}"
            )


def validate_artifact_tree(root: Path, requirements_text: str) -> dict[str, bytes]:
    if not root.is_dir() or root.is_symlink():
        raise GovernanceError("dependency-lock artifact root must be a real directory")

    expected_dirs = {f"{ARTIFACT_PREFIX}{version}{ARTIFACT_SUFFIX}" for version in EXPECTED_PYTHONS}
    actual_dirs = {entry.name for entry in root.iterdir()}
    if actual_dirs != expected_dirs:
        raise GovernanceError(
            f"dependency-lock artifacts must be exactly {sorted(expected_dirs)}, "
            f"found {sorted(actual_dirs)}"
        )

    with tempfile.TemporaryDirectory(prefix="dependency-lock-source-") as temporary:
        source = Path(temporary) / "requirements.txt"
        source.write_text(requirements_text, encoding="utf-8")
        direct = load_direct_requirements(source)

    locks: dict[str, bytes] = {}
    for version in EXPECTED_PYTHONS:
        directory = root / f"{ARTIFACT_PREFIX}{version}{ARTIFACT_SUFFIX}"
        if not directory.is_dir() or directory.is_symlink():
            raise GovernanceError(f"artifact directory for Python {version} is unsafe")
        entries = list(directory.iterdir())
        expected_name = f"python-{version}.txt"
        if len(entries) != 1 or entries[0].name != expected_name:
            raise GovernanceError(
                f"Python {version} artifact must contain exactly {expected_name}"
            )
        path = entries[0]
        if not path.is_file() or path.is_symlink():
            raise GovernanceError(f"Python {version} lock artifact must be a regular file")
        size = path.stat().st_size
        if size <= 0 or size > LOCK_LIMIT_BYTES:
            raise GovernanceError(
                f"Python {version} lock size {size} is outside the accepted resource bound"
            )
        data = path.read_bytes()
        if len(data) != size:
            raise GovernanceError(f"Python {version} lock changed while being read")
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise GovernanceError(f"Python {version} lock is not UTF-8") from exc
        _validate_lock_text(
            python_version=version,
            text=text,
            direct_requirements=direct,
        )
        locks[version] = data
    return locks


def build_manifest(requirements_bytes: bytes, locks: dict[str, bytes]) -> bytes:
    if tuple(sorted(locks)) != EXPECTED_PYTHONS:
        raise GovernanceError("cannot build lock manifest from an incomplete interpreter set")
    manifest = {
        "schemaVersion": 1,
        "generator": {
            "name": "pip-tools",
            "version": "7.6.1",
            "hashMode": "pip --require-hashes",
        },
        "source": {
            "path": "requirements.txt",
            "gitBlob": git_blob_sha_bytes(requirements_bytes),
        },
        "locks": [
            {
                "python": version,
                "path": f"requirements-lock/python-{version}.txt",
                "gitBlob": git_blob_sha_bytes(locks[version]),
            }
            for version in EXPECTED_PYTHONS
        ],
    }
    return (json.dumps(manifest, indent=2) + "\n").encode("utf-8")


def _create_blob(api: GitHubApi, data: bytes) -> str:
    result = api.post(
        "/git/blobs",
        {"content": base64.b64encode(data).decode("ascii"), "encoding": "base64"},
    )
    sha = (result or {}).get("sha")
    if not isinstance(sha, str) or not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise GovernanceError("GitHub did not return a valid blob SHA")
    return sha


def _branch_ref_path(branch: str) -> str:
    if not branch.startswith("dependabot/pip/"):
        raise GovernanceError("publisher accepts dependabot/pip branches only")
    if not re.fullmatch(r"[A-Za-z0-9._/-]+", branch):
        raise GovernanceError("Dependabot branch contains unsupported characters")
    return "/git/refs/heads/" + urllib.parse.quote(branch, safe="/")


def publish_locks(
    api: GitHubApi,
    *,
    pull: dict[str, Any],
    source_head: str,
    locks: dict[str, bytes],
    manifest: bytes,
) -> str:
    head = pull.get("head") or {}
    branch = str(head.get("ref") or "")
    if head.get("sha") != source_head:
        raise GovernanceError("pull-request head moved before lock publication")

    git_commit = api.get(f"/git/commits/{source_head}")
    base_tree = ((git_commit or {}).get("tree") or {}).get("sha")
    if not isinstance(base_tree, str) or not re.fullmatch(r"[0-9a-f]{40}", base_tree):
        raise GovernanceError("cannot resolve source head tree")

    entries: list[dict[str, str]] = []
    for version in EXPECTED_PYTHONS:
        entries.append(
            {
                "path": f"requirements-lock/python-{version}.txt",
                "mode": "100644",
                "type": "blob",
                "sha": _create_blob(api, locks[version]),
            }
        )
    entries.append(
        {
            "path": "requirements-lock/manifest.json",
            "mode": "100644",
            "type": "blob",
            "sha": _create_blob(api, manifest),
        }
    )
    tree = api.post("/git/trees", {"base_tree": base_tree, "tree": entries})
    tree_sha = (tree or {}).get("sha")
    if not isinstance(tree_sha, str) or not re.fullmatch(r"[0-9a-f]{40}", tree_sha):
        raise GovernanceError("GitHub did not return a valid generated tree SHA")

    commit = api.post(
        "/git/commits",
        {
            "message": (
                f"{PUBLISH_MESSAGE}\n\n"
                f"Generated from Dependabot source head {source_head} by trusted default-branch "
                "dependency-lock-publisher."
            ),
            "tree": tree_sha,
            "parents": [source_head],
        },
    )
    commit_sha = (commit or {}).get("sha")
    if not isinstance(commit_sha, str) or not re.fullmatch(r"[0-9a-f]{40}", commit_sha):
        raise GovernanceError("GitHub did not return a valid generated commit SHA")

    ref_path = _branch_ref_path(branch)
    current_ref = api.get(ref_path)
    if ((current_ref or {}).get("object") or {}).get("sha") != source_head:
        raise GovernanceError("Dependabot branch moved before atomic ref publication")
    api.patch(ref_path, {"sha": commit_sha, "force": False})
    return commit_sha


def _resolve_pull_context(
    api: GitHubApi,
    event: dict[str, Any],
    config: dict[str, Any],
) -> tuple[dict[str, Any], str, str]:
    workflow_run = event.get("workflow_run") or {}
    associations = workflow_run.get("pull_requests") or []
    if len(associations) != 1 or not isinstance(associations[0].get("number"), int):
        raise GovernanceError("dependency-lock workflow run must identify exactly one pull request")
    number = associations[0]["number"]
    pull = api.get(f"/pulls/{number}")
    if not isinstance(pull, dict):
        raise GovernanceError("cannot resolve dependency-lock pull request")
    validate_workflow_run(workflow_run, pull, api.repository)

    base = api.get(f"/branches/{urllib.parse.quote(config['baseBranch'], safe='')}")
    base_sha = ((base or {}).get("commit") or {}).get("sha")
    if not isinstance(base_sha, str):
        raise GovernanceError("cannot resolve current base branch head")
    commits = api.paginate(f"/pulls/{number}/commits")
    provenance = validate_provenance(pull, commits, base_sha, config)
    if not provenance["eligible"]:
        raise GovernanceError(
            "dependency-lock publication provenance rejected:\n- "
            + "\n- ".join(provenance["reasons"])
        )
    metadata = validate_signed_metadata(provenance["commit"])
    if not metadata["eligible"]:
        raise GovernanceError(
            "Dependabot signed metadata rejected:\n- " + "\n- ".join(metadata["reasons"])
        )

    files = api.paginate(f"/pulls/{number}/files")
    if classify_ecosystem(files, config) != "pip" or [f.get("filename") for f in files] != [
        "requirements.txt"
    ]:
        raise GovernanceError("lock publisher accepts a requirements.txt-only Dependabot pip diff")

    head_sha = str((pull.get("head") or {}).get("sha") or "")
    requirements_text = api.file_at("requirements.txt", head_sha)
    return pull, head_sha, requirements_text


def _read_event() -> dict[str, Any]:
    path = os.environ.get("GITHUB_EVENT_PATH")
    if not path:
        raise GovernanceError("GITHUB_EVENT_PATH is required")
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise GovernanceError(f"unable to read workflow event: {exc}") from exc


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact-root", type=Path, required=True)
    args = parser.parse_args(argv)

    repository = os.environ.get("GITHUB_REPOSITORY", "")
    token = os.environ.get("GITHUB_TOKEN", "")
    config = load_config()
    api = GitHubApi(token, repository, config["maxPaginationPages"])
    pull, source_head, requirements_text = _resolve_pull_context(api, _read_event(), config)
    locks = validate_artifact_tree(args.artifact_root, requirements_text)
    requirements_bytes = requirements_text.encode("utf-8")
    manifest = build_manifest(requirements_bytes, locks)
    commit_sha = publish_locks(
        api,
        pull=pull,
        source_head=source_head,
        locks=locks,
        manifest=manifest,
    )
    print(
        json.dumps(
            {
                "pull": pull["number"],
                "sourceHead": source_head,
                "generatedCommit": commit_sha,
                "python": list(EXPECTED_PYTHONS),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GovernanceError as exc:
        print(f"dependency-lock publisher error: {exc}", file=os.sys.stderr)
        raise SystemExit(1) from None
