from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from dependency_governance import GovernanceError
from dependency_lock_publisher import (
    EXPECTED_PYTHONS,
    build_manifest,
    git_blob_sha_bytes,
    publish_locks,
    validate_artifact_tree,
    validate_workflow_run,
)

REPOSITORY = "o/r"
HEAD = "b" * 40
BASE = "a" * 40


def pull_fixture() -> dict:
    return {
        "number": 59,
        "head": {
            "sha": HEAD,
            "ref": "dependabot/pip/pytest-rerunfailures-gte-16.6.1-and-lt-17",
            "repo": {"full_name": REPOSITORY},
        },
        "base": {"sha": BASE, "ref": "main", "repo": {"full_name": REPOSITORY}},
    }


def run_fixture() -> dict:
    return {
        "name": "dependency-locks",
        "path": ".github/workflows/dependency-locks.yml",
        "event": "pull_request",
        "conclusion": "success",
        "head_sha": HEAD,
        "head_branch": pull_fixture()["head"]["ref"],
        "head_repository": {"full_name": REPOSITORY},
        "pull_requests": [{"number": 59}],
    }


def lock_text(version: str) -> str:
    return (
        f"# This file is autogenerated by pip-compile with Python {version}\n"
        "pytest==8.4.2 \\\n"
        f"    --hash=sha256:{'1' * 64}\n"
        "ruff==0.16.6 \\\n"
        f"    --hash=sha256:{'2' * 64}\n"
    )


def artifact_tree(root: Path) -> None:
    for version in EXPECTED_PYTHONS:
        directory = root / f"python-{version}-lock"
        directory.mkdir()
        (directory / f"python-{version}.txt").write_text(lock_text(version), encoding="utf-8")


class FakeApi:
    def __init__(self, *, ref_sha: str = HEAD) -> None:
        self.ref_sha = ref_sha
        self.posts: list[tuple[str, dict]] = []
        self.patches: list[tuple[str, dict]] = []
        self.blob_index = 0

    def get(self, path: str) -> dict:
        if path == f"/git/commits/{HEAD}":
            return {"tree": {"sha": "c" * 40}}
        if path.startswith("/git/refs/heads/"):
            return {"object": {"sha": self.ref_sha}}
        raise AssertionError(f"unexpected GET {path}")

    def post(self, path: str, payload: dict) -> dict:
        self.posts.append((path, payload))
        if path == "/git/blobs":
            self.blob_index += 1
            return {"sha": f"{self.blob_index:040x}"}
        if path == "/git/trees":
            return {"sha": "d" * 40}
        if path == "/git/commits":
            return {"sha": "e" * 40}
        raise AssertionError(f"unexpected POST {path}")

    def patch(self, path: str, payload: dict) -> dict:
        self.patches.append((path, payload))
        return {"object": {"sha": payload["sha"]}}


class DependencyLockPublisherTests(unittest.TestCase):
    def test_workflow_run_binds_exact_path_head_branch_repository_and_pr(self) -> None:
        validate_workflow_run(run_fixture(), pull_fixture(), REPOSITORY)
        for mutation in (
            {"path": ".github/workflows/fake.yml"},
            {"head_sha": "c" * 40},
            {"head_branch": "dependabot/pip/other"},
            {"head_repository": {"full_name": "evil/fork"}},
            {"pull_requests": [{"number": 999}]},
            {"event": "push"},
            {"conclusion": "failure"},
        ):
            with self.assertRaises(GovernanceError):
                validate_workflow_run({**run_fixture(), **mutation}, pull_fixture(), REPOSITORY)

    def test_artifacts_require_exact_interpreter_set_and_source_compatible_pins(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            artifact_tree(root)
            locks = validate_artifact_tree(root, "pytest>=8,<9\nruff>=0.16,<1\n")
            self.assertEqual(tuple(sorted(locks)), EXPECTED_PYTHONS)
            (root / "unexpected-lock").mkdir()
            with self.assertRaises(GovernanceError):
                validate_artifact_tree(root, "pytest>=8,<9\nruff>=0.16,<1\n")

    def test_artifacts_reject_missing_hash_and_out_of_constraint_direct_pin(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            artifact_tree(root)
            target = root / "python-3.11-lock" / "python-3.11.txt"
            target.write_text(
                lock_text("3.11").replace("--hash=sha256:", "--digest=sha256:"),
                encoding="utf-8",
            )
            with self.assertRaises(GovernanceError):
                validate_artifact_tree(root, "pytest>=8,<9\nruff>=0.16,<1\n")

        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            artifact_tree(root)
            target = root / "python-3.12-lock" / "python-3.12.txt"
            target.write_text(lock_text("3.12").replace("ruff==0.16.6", "ruff==2.0.0"), encoding="utf-8")
            with self.assertRaises(GovernanceError):
                validate_artifact_tree(root, "pytest>=8,<9\nruff>=0.16,<1\n")

    def test_manifest_binds_source_and_every_generated_lock_blob(self) -> None:
        requirements = b"pytest>=8,<9\nruff>=0.16,<1\n"
        locks = {version: lock_text(version).encode() for version in EXPECTED_PYTHONS}
        manifest = json.loads(build_manifest(requirements, locks))
        self.assertEqual(manifest["source"]["gitBlob"], git_blob_sha_bytes(requirements))
        self.assertEqual([entry["python"] for entry in manifest["locks"]], list(EXPECTED_PYTHONS))
        for entry in manifest["locks"]:
            self.assertEqual(entry["gitBlob"], git_blob_sha_bytes(locks[entry["python"]]))

    def test_atomic_publication_updates_only_after_exact_ref_recheck(self) -> None:
        locks = {version: lock_text(version).encode() for version in EXPECTED_PYTHONS}
        manifest = build_manifest(b"pytest>=8,<9\nruff>=0.16,<1\n", locks)
        api = FakeApi()
        commit = publish_locks(
            api, pull=pull_fixture(), source_head=HEAD, locks=locks, manifest=manifest
        )
        self.assertEqual(commit, "e" * 40)
        self.assertEqual(len([path for path, _ in api.posts if path == "/git/blobs"]), 5)
        tree_payload = next(payload for path, payload in api.posts if path == "/git/trees")
        self.assertEqual(
            {entry["path"] for entry in tree_payload["tree"]},
            {*(f"requirements-lock/python-{v}.txt" for v in EXPECTED_PYTHONS), "requirements-lock/manifest.json"},
        )
        self.assertEqual(api.patches[0][1], {"sha": "e" * 40, "force": False})

        raced = FakeApi(ref_sha="f" * 40)
        with self.assertRaisesRegex(GovernanceError, "branch moved"):
            publish_locks(
                raced, pull=pull_fixture(), source_head=HEAD, locks=locks, manifest=manifest
            )
        self.assertEqual(raced.patches, [])


if __name__ == "__main__":
    unittest.main()
