from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

try:
    from packaging.markers import default_environment
    from packaging.requirements import Requirement
except ModuleNotFoundError:  # pip vendors packaging on supported CI interpreters.
    from pip._vendor.packaging.markers import default_environment
    from pip._vendor.packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / "requirements-lock" / "manifest.json"
EXPECTED_PYTHONS = {"3.11", "3.12", "3.13"}
PIN_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s\\]+)", re.MULTILINE)


def canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def git_blob_sha(path: Path) -> str:
    data = path.read_bytes()
    header = f"blob {len(data)}\0".encode()
    return hashlib.sha1(header + data).hexdigest()


def load_direct_requirements(path: Path) -> list[Requirement]:
    requirements: list[Requirement] = []
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith(("-", "--")):
            raise SystemExit(
                f"unsupported requirements directive at {path}:{line_number}: {line}"
            )
        try:
            requirements.append(Requirement(line))
        except Exception as exc:  # pragma: no cover - defensive parse boundary
            raise SystemExit(
                f"invalid requirement at {path}:{line_number}: {line}: {exc}"
            ) from exc
    return requirements


def marker_environment(python_version: str) -> dict[str, str]:
    environment = default_environment()
    environment["python_version"] = python_version
    environment["python_full_version"] = f"{python_version}.0"
    return environment


def validate_lock(
    *, python_version: str, path: Path, expected_blob: str, direct: list[Requirement]
) -> None:
    actual_blob = git_blob_sha(path)
    if actual_blob != expected_blob:
        raise SystemExit(
            f"stale lock manifest for {path.relative_to(ROOT)}: "
            f"expected blob {expected_blob}, found {actual_blob}"
        )

    text = path.read_text(encoding="utf-8")
    expected_header = f"autogenerated by pip-compile with Python {python_version}"
    if expected_header not in text:
        raise SystemExit(f"{path.relative_to(ROOT)} does not identify Python {python_version}")
    if "--hash=sha256:" not in text:
        raise SystemExit(f"{path.relative_to(ROOT)} does not contain package hashes")

    pins = {canonical_name(name): version for name, version in PIN_RE.findall(text)}
    if not pins:
        raise SystemExit(f"{path.relative_to(ROOT)} contains no exact package pins")

    environment = marker_environment(python_version)
    for requirement in direct:
        if requirement.marker and not requirement.marker.evaluate(environment=environment):
            continue
        name = canonical_name(requirement.name)
        pinned = pins.get(name)
        if pinned is None:
            raise SystemExit(
                f"{path.relative_to(ROOT)} is missing direct requirement {requirement.name}"
            )
        if requirement.specifier and not requirement.specifier.contains(pinned, prereleases=True):
            raise SystemExit(
                f"{path.relative_to(ROOT)} pins {requirement.name}=={pinned}, "
                f"outside direct constraint {requirement.specifier}"
            )


def main() -> None:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    if manifest.get("schemaVersion") != 1:
        raise SystemExit("unsupported dependency lock manifest schema")

    generator = manifest.get("generator", {})
    if generator.get("name") != "pip-tools" or generator.get("version") != "7.6.1":
        raise SystemExit("dependency lock generator identity drifted")

    source = manifest.get("source", {})
    source_path = ROOT / source.get("path", "")
    if source_path != ROOT / "requirements.txt":
        raise SystemExit("dependency lock manifest must be rooted in requirements.txt")
    if git_blob_sha(source_path) != source.get("gitBlob"):
        raise SystemExit(
            "requirements.txt changed without regenerating the supported-interpreter locks "
            "and requirements-lock/manifest.json"
        )

    direct = load_direct_requirements(source_path)
    locks = manifest.get("locks")
    if not isinstance(locks, list):
        raise SystemExit("dependency lock manifest must contain a locks list")

    versions = {entry.get("python") for entry in locks if isinstance(entry, dict)}
    if versions != EXPECTED_PYTHONS or len(locks) != len(EXPECTED_PYTHONS):
        raise SystemExit(
            f"expected exactly {sorted(EXPECTED_PYTHONS)} lock entries, found {sorted(versions)}"
        )

    seen_paths: set[str] = set()
    for entry in locks:
        python_version = entry["python"]
        relative_path = entry["path"]
        expected_path = f"requirements-lock/python-{python_version}.txt"
        if relative_path != expected_path:
            raise SystemExit(
                f"unexpected lock path for Python {python_version}: {relative_path}"
            )
        if relative_path in seen_paths:
            raise SystemExit(f"duplicate lock path in manifest: {relative_path}")
        seen_paths.add(relative_path)
        validate_lock(
            python_version=python_version,
            path=ROOT / relative_path,
            expected_blob=entry["gitBlob"],
            direct=direct,
        )

    print(
        "validated dependency-lock provenance and direct constraints for Python "
        + ", ".join(sorted(EXPECTED_PYTHONS))
    )


if __name__ == "__main__":
    main()
