name: Python Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
          docker run -u zap -d -p 8090:8090 \
            -e ZAP_PORT=8090 \
            ghcr.io/zaproxy/zaproxy:bare \
            zap.sh -daemon -port 8090 -config api.disablekey=true
          pytest -q
