name: Python Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run unit tests
        run: pytest -m unit -v

      - name: Run API tests
        run: pytest -m api -v

      - name: Run database tests
        run: pytest -m db -v

      - name: Run UI tests
        run: pytest -m e2e -v

      - name: Run performance tests
        run: pytest -m performance -v

      - name: Run security tests
        run: pytest -m security -v

      - name: Run unmarked tests
        run: pytest -v
